env: local
pages:
  login:
    enable: true
    title: "哈哈"
remoteConfig:
  enable: false
  remoteConfigName: test
  
  apiKey: "**"
  authDomain: "**"
  databaseURL: "**"
  projectId: "**"
  storageBucket: "**"
  messagingSenderId: "**"
  appId: "**"
  measurementId: "**"
